# Generated by Django 3.1.2 on 2020-10-07 10:19

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
