# Generated by Django 3.1.2 on 2020-10-19 04:03

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='person_photo',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.get_file_path),
        ),
    ]
